### ISSUE TITLE
Starting from cycle x 

### ISSUE THREAD

**Issue by 10Xtz** [dakk/tezpool#1]
Start from a specific cycle, based on when the delegate started.

Add to:
config.json

```
"startcycle": 7,
```

Edit:
tezpool.py
"lastcycle", lines 149 and 154
lastcycle = conf['startcycle']

```
		data = {
			"cycles": []
		}
		lastcycle = conf['startcycle']
	except:
		data = {
			"cycles": []
		}
		lastcycle = conf['startcycle']

```

line 188
cycle
```
data = { 'cycle': conf['startcycle'] - 1, 'frozen': 0, 'frozenminusfee': 0, 'pendingminusfee': 0, 'pending': 0, 'paid': 0, 'deleguees': {}, 'cycles': {} }
```

**Comment by dakk** [comment]
Good point; I'll release a fix for this today

**Comment by dakk** [comment]
https://github.com/dakk/tezpool/commit/d227565ddba4510c269c67f03f49c7576b72d455
