### ISSUE TITLE
Some improvements needed

### ISSUE THREAD

**Issue by ericlavoie** [dakk/tezpool#2]
Hi, love the script it is great.
Here is a few improvement i can suggest:
For each cycle auto fill the delegate list, too many changes makes manually filling the config file tedious.
paypendings does not list distibution of pending rewards it seems to only list paid rewards, i think it would be good to list a distribution of pending rewards, and paid rewards, add another command maybe to just list paid rewards.

**Comment by utdrmac** [comment]
Reverse the order of cycle information. Latest cycle should be at the top. A pain to have to constantly scroll down through all that older stuff.
