### ISSUE TITLE
Pending rewards always remain at 0

### ISSUE THREAD

**Issue by ericlavoie** [dakk/tezpool#3]
You seem to have an error in the differentiation with pending versus deposit frozen.

**Comment by dakk** [comment]
The "pending" value is the baked reward after 7 frozen cycles
The "frozen" value si the baked reward still frozen
The "paid" value is the pending value already sent to delegators

**Comment by ericlavoie** [comment]
check http://tzscan.io/tz1SohptP53wDPZhzTWzDUFAUcWF6DMBpaJV?default=rewards

for cycle 14 the output is the following:
Estimated =  12 (its fine) 
Frozen = 12 (that is incorrect, it should be 84 if it is deposits, otherwise there is no need for pending)
Pending =  0, (it should be 12) 
Paid reward = 0 (correct) (tzscan uses deliverred)
This terminology is the one used by tzscan.

**Comment by ericlavoie** [comment]
Also could the output allow filtering for one specific key?

**Comment by dakk** [comment]
frozen is not the deposit; it's the reward not yet mature

**Comment by ericlavoie** [comment]
This causes confusion, the reference seems to be tzscan, and frozen is reward pending, estimated is equivalent to pending.
You do not show pending value at any cycle, paid reward is not there either, but reward is, this is way too mixed or rather not consistent across your interface.

**Comment by dakk** [comment]
Btw tzscan it's not a pool and doesn't include pending reward to be redistributed and paid reward to deleguees; anyway I put a small dictionary in the readme: https://github.com/dakk/tezpool#terms

**Comment by ericlavoie** [comment]
Actually tzscan shows delegates payments, and pending reward distribution
see http://tzscan.io/tz1SohptP53wDPZhzTWzDUFAUcWF6DMBpaJV?default=rewards
