### ISSUE TITLE
[Features request] Add custom path & account name + skip address

### ISSUE THREAD

**Issue by gregorst3** [dakk/tezpool#9]
Hello, 
 is it possible to add custom path for the tezos client process and custom account name instead of 
 "my_account"?  
(Please refer to [L279](https://github.com/dakk/tezpool/blob/master/tezpool.py#L279))

Also is it possible to add a skip - blacklist address function?
(Ex: baker exceeded maximum cap and wants to blacklist new voters)

**Comment by dakk** [comment]
done; it's now configurable from config.json['payout']
